-- Repwise — exercise library seed
--
-- Run AFTER 0001_init.sql. Safe to re-run: every row upserts on `slug`.
--
-- Deliberately balanced between home-viable equipment (bodyweight, dumbbell,
-- band, pull-up bar) and gym equipment (barbell, machine, cable). The AI plan
-- generator may only choose exercises from this table whose `equipment` is in
-- the user's `available_equipment`, so a thin home section here would produce
-- thin home plans.

insert into public.exercises
  (slug, name, primary_muscle, secondary_muscles, equipment, is_bodyweight, is_compound, difficulty, instructions)
values
-- ============================== CHEST ==============================
('push-up', 'Push-Up', 'chest', '{triceps,shoulders,core}', 'bodyweight', true, true, 'beginner',
 'Hands slightly wider than shoulders. Keep a straight line from head to heels, brace the core, lower until the chest is just above the floor, then press away.'),
('incline-push-up', 'Incline Push-Up', 'chest', '{triceps,shoulders}', 'bodyweight', true, true, 'beginner',
 'Hands elevated on a bench, step or sturdy table. The higher the hands, the easier the movement — the go-to regression for a first push-up.'),
('decline-push-up', 'Decline Push-Up', 'chest', '{shoulders,triceps}', 'bodyweight', true, true, 'intermediate',
 'Feet elevated on a chair or bench. Shifts load toward the upper chest and front delts.'),
('diamond-push-up', 'Diamond Push-Up', 'triceps', '{chest,shoulders}', 'bodyweight', true, true, 'intermediate',
 'Hands together under the chest forming a diamond. Keep elbows tucked close to the ribs.'),
('dumbbell-bench-press', 'Dumbbell Bench Press', 'chest', '{triceps,shoulders}', 'dumbbell', false, true, 'beginner',
 'Lie on a bench, dumbbells at chest level, wrists stacked over elbows. Press up and slightly together without locking out hard.'),
('dumbbell-floor-press', 'Dumbbell Floor Press', 'chest', '{triceps}', 'dumbbell', false, true, 'beginner',
 'Bench-press variation performed lying on the floor. The floor limits the range of motion, which is easier on the shoulders and needs no bench.'),
('dumbbell-fly', 'Dumbbell Fly', 'chest', '{shoulders}', 'dumbbell', false, false, 'intermediate',
 'Slight bend in the elbows held constant. Open the arms wide in an arc, feel the stretch, then hug them back together.'),
('incline-dumbbell-press', 'Incline Dumbbell Press', 'chest', '{shoulders,triceps}', 'dumbbell', false, true, 'intermediate',
 'Bench set to roughly 30 degrees. Emphasises the upper chest.'),
('barbell-bench-press', 'Barbell Bench Press', 'chest', '{triceps,shoulders}', 'barbell', false, true, 'intermediate',
 'Shoulder blades retracted and pinned to the bench, feet planted. Lower to mid-chest with control, press back to lockout. Use a spotter when going heavy.'),
('incline-barbell-press', 'Incline Barbell Press', 'chest', '{shoulders,triceps}', 'barbell', false, true, 'intermediate',
 'Bench at 30-45 degrees. Bar touches the upper chest just below the collarbone.'),
('chest-press-machine', 'Chest Press Machine', 'chest', '{triceps,shoulders}', 'machine', false, true, 'beginner',
 'Seat height set so the handles sit level with mid-chest. The fixed path makes this a safe heavy option without a spotter.'),
('cable-crossover', 'Cable Crossover', 'chest', '{shoulders}', 'cable', false, false, 'intermediate',
 'Pulleys set high, slight forward lean. Sweep the handles down and together in front of the hips.'),
('band-chest-press', 'Resistance Band Chest Press', 'chest', '{triceps,shoulders}', 'resistance_band', false, true, 'beginner',
 'Anchor the band behind you at chest height. Press forward until the arms are straight, resisting the return.'),

-- ============================== BACK ==============================
('pull-up', 'Pull-Up', 'back', '{biceps,forearms}', 'pull_up_bar', true, true, 'advanced',
 'Overhand grip just wider than shoulders. Pull the elbows down to the ribs until the chin clears the bar, lower under control.'),
('chin-up', 'Chin-Up', 'back', '{biceps}', 'pull_up_bar', true, true, 'intermediate',
 'Underhand grip, shoulder width. Slightly easier than a pull-up and heavier on the biceps.'),
('inverted-row', 'Inverted Row', 'back', '{biceps,core}', 'bodyweight', true, true, 'beginner',
 'Lie under a bar or sturdy table, body straight, pull the chest to the edge. Walk the feet in to make it easier.'),
('superman', 'Superman', 'back', '{glutes,hamstrings}', 'bodyweight', true, false, 'beginner',
 'Face down, lift the chest, arms and thighs off the floor together. Hold briefly at the top.'),
('dumbbell-row', 'Single-Arm Dumbbell Row', 'back', '{biceps,forearms}', 'dumbbell', false, true, 'beginner',
 'One knee and hand on a bench, back flat. Pull the dumbbell to the hip, keeping the elbow close to the body.'),
('dumbbell-bent-over-row', 'Bent-Over Dumbbell Row', 'back', '{biceps,core}', 'dumbbell', false, true, 'intermediate',
 'Hinge at the hips to roughly 45 degrees, spine neutral. Row both dumbbells to the lower ribs.'),
('dumbbell-pullover', 'Dumbbell Pullover', 'back', '{chest,triceps}', 'dumbbell', false, false, 'intermediate',
 'Lie across or along a bench, arms nearly straight. Lower one dumbbell behind the head, then pull it back over the chest.'),
('barbell-row', 'Barbell Bent-Over Row', 'back', '{biceps,core}', 'barbell', false, true, 'intermediate',
 'Hinge forward with a flat back, bar hanging at arm''s length. Row to the navel and lower with control.'),
('deadlift', 'Barbell Deadlift', 'back', '{hamstrings,glutes,core,forearms}', 'barbell', false, true, 'advanced',
 'Bar over mid-foot, flat back, chest up. Drive the floor away with the legs and lock out with the hips. Technique before load, always.'),
('lat-pulldown', 'Lat Pulldown', 'back', '{biceps}', 'cable', false, true, 'beginner',
 'Grip wider than shoulders. Pull the bar to the upper chest, driving the elbows down and back. The best pull-up substitute while building strength.'),
('seated-cable-row', 'Seated Cable Row', 'back', '{biceps,forearms}', 'cable', false, true, 'beginner',
 'Chest tall, slight backward lean. Pull the handle to the navel and squeeze the shoulder blades together.'),
('band-lat-pulldown', 'Band Lat Pulldown', 'back', '{biceps}', 'resistance_band', false, true, 'beginner',
 'Anchor the band overhead. Kneel and pull the ends down to the shoulders, driving the elbows toward the ribs.'),
('band-row', 'Seated Band Row', 'back', '{biceps}', 'resistance_band', false, true, 'beginner',
 'Sit with legs extended, band looped around the feet. Row the handles to the waist.'),

-- ============================== SHOULDERS ==============================
('pike-push-up', 'Pike Push-Up', 'shoulders', '{triceps,chest}', 'bodyweight', true, true, 'intermediate',
 'Hips high in an inverted V. Lower the crown of the head toward the floor and press back up — the bodyweight overhead press.'),
('dumbbell-shoulder-press', 'Dumbbell Shoulder Press', 'shoulders', '{triceps,core}', 'dumbbell', false, true, 'beginner',
 'Seated or standing, dumbbells at ear height. Press overhead without flaring the ribs.'),
('lateral-raise', 'Dumbbell Lateral Raise', 'shoulders', '{}', 'dumbbell', false, false, 'beginner',
 'Slight elbow bend, raise the arms out to the sides to shoulder height. Lead with the elbows, not the hands.'),
('front-raise', 'Dumbbell Front Raise', 'shoulders', '{}', 'dumbbell', false, false, 'beginner',
 'Raise the dumbbells straight in front to shoulder height with a controlled tempo.'),
('rear-delt-fly', 'Bent-Over Rear Delt Fly', 'shoulders', '{back}', 'dumbbell', false, false, 'intermediate',
 'Hinge forward, arms hanging. Sweep the dumbbells out and back, squeezing the rear shoulders.'),
('arnold-press', 'Arnold Press', 'shoulders', '{triceps}', 'dumbbell', false, true, 'intermediate',
 'Start with palms facing you, rotate outward as you press overhead. Hits all three deltoid heads.'),
('overhead-press', 'Barbell Overhead Press', 'shoulders', '{triceps,core}', 'barbell', false, true, 'intermediate',
 'Bar at collarbone height, glutes and core braced. Press straight overhead, moving the head slightly back then through.'),
('upright-row', 'Cable Upright Row', 'shoulders', '{traps,biceps}', 'cable', false, true, 'intermediate',
 'Pull the bar up along the body to chest height, elbows leading. Stop if it pinches the shoulder.'),
('face-pull', 'Cable Face Pull', 'shoulders', '{back}', 'cable', false, false, 'beginner',
 'Rope at face height. Pull toward the forehead, splitting the hands apart. Excellent posture and shoulder-health work.'),
('band-lateral-raise', 'Band Lateral Raise', 'shoulders', '{}', 'resistance_band', false, false, 'beginner',
 'Stand on the band, raise the arms out to the sides against the resistance.'),

-- ============================== LEGS ==============================
('bodyweight-squat', 'Bodyweight Squat', 'quadriceps', '{glutes,core}', 'bodyweight', true, true, 'beginner',
 'Feet shoulder width, toes slightly out. Sit back and down keeping the chest up and knees tracking over the toes.'),
('lunge', 'Walking Lunge', 'quadriceps', '{glutes,hamstrings}', 'bodyweight', true, true, 'beginner',
 'Step forward, drop the back knee toward the floor, drive through the front heel to stand.'),
('bulgarian-split-squat', 'Bulgarian Split Squat', 'quadriceps', '{glutes,hamstrings}', 'bodyweight', true, true, 'intermediate',
 'Rear foot elevated on a bench or chair. Lower straight down over the front leg. Brutal, and one of the best single-leg builders.'),
('glute-bridge', 'Glute Bridge', 'glutes', '{hamstrings,core}', 'bodyweight', true, false, 'beginner',
 'Lie on the back, feet flat. Drive the hips up until the body forms a straight line, squeeze the glutes at the top.'),
('single-leg-glute-bridge', 'Single-Leg Glute Bridge', 'glutes', '{hamstrings,core}', 'bodyweight', true, false, 'intermediate',
 'One foot planted, the other leg extended. Drive the hips up with a single leg.'),
('wall-sit', 'Wall Sit', 'quadriceps', '{glutes}', 'bodyweight', true, false, 'beginner',
 'Back flat to a wall, thighs parallel to the floor. Hold for time.'),
('calf-raise', 'Standing Calf Raise', 'calves', '{}', 'bodyweight', true, false, 'beginner',
 'Rise onto the toes as high as possible, pause, lower slowly. Use a step for a deeper stretch.'),
('step-up', 'Step-Up', 'quadriceps', '{glutes,hamstrings}', 'bodyweight', true, true, 'beginner',
 'Step onto a sturdy box or bench, driving through the top heel. Control the way down.'),
('goblet-squat', 'Goblet Squat', 'quadriceps', '{glutes,core}', 'dumbbell', false, true, 'beginner',
 'Hold one dumbbell at chest height. The front load makes it easier to stay upright than a back squat.'),
('dumbbell-romanian-deadlift', 'Dumbbell Romanian Deadlift', 'hamstrings', '{glutes,back}', 'dumbbell', false, true, 'beginner',
 'Soft knees, push the hips back and slide the dumbbells down the thighs. Feel the hamstring stretch, then drive the hips forward.'),
('dumbbell-lunge', 'Dumbbell Lunge', 'quadriceps', '{glutes,hamstrings}', 'dumbbell', false, true, 'intermediate',
 'Lunge holding a dumbbell in each hand at the sides.'),
('dumbbell-calf-raise', 'Dumbbell Calf Raise', 'calves', '{}', 'dumbbell', false, false, 'beginner',
 'Hold dumbbells at the sides and rise onto the toes. Add a step for range of motion.'),
('barbell-back-squat', 'Barbell Back Squat', 'quadriceps', '{glutes,hamstrings,core}', 'barbell', false, true, 'intermediate',
 'Bar on the upper traps, brace hard, sit down between the hips. Depth to at least parallel if mobility allows.'),
('barbell-front-squat', 'Barbell Front Squat', 'quadriceps', '{core,glutes}', 'barbell', false, true, 'advanced',
 'Bar racked on the front delts, elbows high. More upright than a back squat and far more quad-dominant.'),
('romanian-deadlift', 'Barbell Romanian Deadlift', 'hamstrings', '{glutes,back}', 'barbell', false, true, 'intermediate',
 'From standing, hinge at the hips with a flat back, bar tracking the legs. Stop when the hamstrings run out of stretch.'),
('hip-thrust', 'Barbell Hip Thrust', 'glutes', '{hamstrings}', 'barbell', false, true, 'intermediate',
 'Upper back on a bench, bar across the hips with a pad. Drive the hips to full extension and squeeze.'),
('leg-press', 'Leg Press', 'quadriceps', '{glutes,hamstrings}', 'machine', false, true, 'beginner',
 'Feet shoulder width on the platform. Lower until the knees reach about 90 degrees, press back without locking out hard.'),
('leg-curl', 'Lying Leg Curl', 'hamstrings', '{calves}', 'machine', false, false, 'beginner',
 'Curl the heels toward the glutes against the pad, lower slowly.'),
('leg-extension', 'Leg Extension', 'quadriceps', '{}', 'machine', false, false, 'beginner',
 'Extend the knees to straight, pause at the top, lower under control.'),
('seated-calf-raise', 'Seated Calf Raise', 'calves', '{}', 'machine', false, false, 'beginner',
 'Knees bent under the pad. Targets the soleus, the deeper calf muscle.'),
('band-squat', 'Band Squat', 'quadriceps', '{glutes}', 'resistance_band', false, true, 'beginner',
 'Stand on the band, ends at the shoulders. Squat against the added tension.'),

-- ============================== ARMS ==============================
('bench-dip', 'Bench Dip', 'triceps', '{chest,shoulders}', 'bodyweight', true, true, 'beginner',
 'Hands on a bench behind you, legs extended. Lower the hips until the elbows reach 90 degrees, press back up.'),
('close-grip-push-up', 'Close-Grip Push-Up', 'triceps', '{chest}', 'bodyweight', true, true, 'intermediate',
 'Push-up with the hands under the shoulders and elbows tracking backward.'),
('dumbbell-curl', 'Dumbbell Biceps Curl', 'biceps', '{forearms}', 'dumbbell', false, false, 'beginner',
 'Elbows pinned at the sides. Curl up without swinging, lower slowly.'),
('hammer-curl', 'Hammer Curl', 'biceps', '{forearms}', 'dumbbell', false, false, 'beginner',
 'Neutral grip, palms facing each other. Emphasises the brachialis and forearm.'),
('concentration-curl', 'Concentration Curl', 'biceps', '{}', 'dumbbell', false, false, 'intermediate',
 'Seated, elbow braced against the inner thigh. Strict, isolated curl.'),
('overhead-triceps-extension', 'Overhead Triceps Extension', 'triceps', '{}', 'dumbbell', false, false, 'beginner',
 'One dumbbell held overhead in both hands. Lower behind the head, keeping the elbows pointing up.'),
('dumbbell-kickback', 'Triceps Kickback', 'triceps', '{}', 'dumbbell', false, false, 'beginner',
 'Hinge forward, upper arm parallel to the torso. Extend the elbow straight back and squeeze.'),
('barbell-curl', 'Barbell Curl', 'biceps', '{forearms}', 'barbell', false, false, 'beginner',
 'Shoulder-width grip, elbows fixed. Curl the bar to chest height without leaning back.'),
('skull-crusher', 'Skull Crusher', 'triceps', '{}', 'barbell', false, false, 'intermediate',
 'Lying, bar over the forehead. Bend at the elbows only, lowering toward the hairline.'),
('cable-triceps-pushdown', 'Cable Triceps Pushdown', 'triceps', '{}', 'cable', false, false, 'beginner',
 'Elbows tucked, push the bar or rope down to full extension and squeeze.'),
('cable-curl', 'Cable Biceps Curl', 'biceps', '{forearms}', 'cable', false, false, 'beginner',
 'Constant tension throughout the curl, which free weights lose at the top.'),
('band-curl', 'Band Biceps Curl', 'biceps', '{forearms}', 'resistance_band', false, false, 'beginner',
 'Stand on the band and curl the handles, resisting on the way down.'),

-- ============================== CORE ==============================
('plank', 'Plank', 'core', '{shoulders,glutes}', 'bodyweight', true, false, 'beginner',
 'Forearms and toes on the floor, body in a straight line. Squeeze the glutes and brace — do not let the hips sag.'),
('side-plank', 'Side Plank', 'core', '{shoulders}', 'bodyweight', true, false, 'beginner',
 'On one forearm, hips stacked and lifted. Targets the obliques.'),
('dead-bug', 'Dead Bug', 'core', '{}', 'bodyweight', true, false, 'beginner',
 'On the back, arms up and knees at 90 degrees. Extend the opposite arm and leg while keeping the lower back flat.'),
('bicycle-crunch', 'Bicycle Crunch', 'core', '{}', 'bodyweight', true, false, 'beginner',
 'Alternate bringing each elbow toward the opposite knee with a slow, controlled twist.'),
('leg-raise', 'Lying Leg Raise', 'core', '{}', 'bodyweight', true, false, 'intermediate',
 'On the back, legs straight. Raise to vertical and lower without letting the lower back arch.'),
('hanging-knee-raise', 'Hanging Knee Raise', 'core', '{forearms}', 'pull_up_bar', true, false, 'intermediate',
 'Hang from the bar, draw the knees up toward the chest by curling the pelvis.'),
('mountain-climber', 'Mountain Climber', 'core', '{shoulders,quadriceps}', 'bodyweight', true, true, 'beginner',
 'From a push-up position, drive the knees toward the chest alternately at pace.'),
('russian-twist', 'Russian Twist', 'core', '{}', 'bodyweight', true, false, 'beginner',
 'Seated, leaning back, feet off the floor. Rotate the torso side to side. Hold a weight to progress.'),
('ab-wheel-rollout', 'Ab Wheel Rollout', 'core', '{shoulders,back}', 'bodyweight', true, true, 'advanced',
 'From the knees, roll out as far as control allows with a flat back, then pull back in.'),
('cable-crunch', 'Cable Crunch', 'core', '{}', 'cable', false, false, 'intermediate',
 'Kneeling under a high pulley, rope at the head. Crunch by flexing the spine, not pulling with the arms.'),

-- ============================== CONDITIONING ==============================
('burpee', 'Burpee', 'full_body', '{chest,quadriceps,core}', 'bodyweight', true, true, 'intermediate',
 'Squat, kick back to a plank, push-up, jump the feet in, jump up. The full-body conditioning staple.'),
('jumping-jack', 'Jumping Jack', 'full_body', '{calves,shoulders}', 'bodyweight', true, true, 'beginner',
 'Jump the feet wide while raising the arms overhead. Simple, effective warm-up.'),
('high-knees', 'High Knees', 'full_body', '{quadriceps,core}', 'bodyweight', true, true, 'beginner',
 'Run in place driving the knees to hip height at pace.'),
('jump-squat', 'Jump Squat', 'quadriceps', '{glutes,calves}', 'bodyweight', true, true, 'intermediate',
 'Squat down then explode into a jump, landing softly straight back into the next rep.'),
('kettlebell-swing', 'Kettlebell Swing', 'glutes', '{hamstrings,core,back}', 'kettlebell', false, true, 'intermediate',
 'Hip hinge, not a squat. Snap the hips forward to float the bell to chest height, let it fall back between the legs.'),
('kettlebell-goblet-squat', 'Kettlebell Goblet Squat', 'quadriceps', '{glutes,core}', 'kettlebell', false, true, 'beginner',
 'Hold the bell by the horns at chest height and squat.'),
('farmers-carry', 'Farmer''s Carry', 'core', '{forearms,traps}', 'dumbbell', false, true, 'beginner',
 'Walk with a heavy dumbbell in each hand, shoulders back and core braced.'),
('medicine-ball-slam', 'Medicine Ball Slam', 'full_body', '{core,shoulders}', 'medicine_ball', false, true, 'beginner',
 'Raise the ball overhead and slam it down hard, catching the bounce or picking it back up.')

on conflict (slug) do update set
  name              = excluded.name,
  primary_muscle    = excluded.primary_muscle,
  secondary_muscles = excluded.secondary_muscles,
  equipment         = excluded.equipment,
  is_bodyweight     = excluded.is_bodyweight,
  is_compound       = excluded.is_compound,
  difficulty        = excluded.difficulty,
  instructions      = excluded.instructions;
